# Generated by Django 5.1.4 on 2024-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("food", "Продовольча"),
                            ("non_food", "Непродовольча"),
                        ],
                        max_length=8,
                    ),
                ),
                ("photo", models.ImageField(upload_to="products/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
