# Generated by Django 5.1.4 on 2024-12-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_cart_customuser_cartitem_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
