# Generated by Django 5.1.4 on 2025-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_product_group_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="765765", verbose_name="Опис Продукту"),
            preserve_default=False,
        ),
    ]
