# Generated by Django 5.1.4 on 2025-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_product_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Кошик", "verbose_name_plural": "Кошик"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукти", "verbose_name_plural": "Продукт"},
        ),
        migrations.AddField(
            model_name="category",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
